[tool.poetry]
name = "mafia-backend"
version = "0.1.0"
description = "Mafia backend"
authors = ["Core Team Mafia"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.116.1"
uvicorn = {extras=["standard"], version="^0.30.6"}
pydantic = "^2.9.0"
pydantic-settings = "^2.5.0"
SQLAlchemy = "^2.0.43"
asyncpg = "^0.29.0"
alembic = "^1.13.0"
redis = "^5.0.0"
sse-starlette = "^2.0"
python-socketio = {version="^5.11.0", extras=["asgi"]}
structlog = "^24.0.0"

[tool.poetry.group.dev.dependencies]
# тесты добавим позже

[tool.ruff]
line-length = 100
target-version = "py312"
extend-select = ["I", "UP"]

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
strict_optional = true
warn_unused_ignores = true
